parameters:
#    acme2_test.example.class: Acme2\TestBundle\Example

services:
#    acme2_test.example:
#        class: %acme2_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
